# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				panda = true
				axolotl = true
				bee = true
				egg = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				llama = true
				bat = true
				husk = true
				hoglin = true
				rabbit = true
				firework_rocket = true
				silverfish = true
				armor_stand = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				turtle = true
				salmon = true
				wandering_trader = true
				piglin_brute = true
				goat = true
				ocelot = true
				item_frame = true
				vindicator = true
				horse = true
				phantom = true
				leash_knot = true
				mooshroom = true
				llama_spit = true
				glow_squid = true
				glow_item_frame = false
				squid = true
				snowball = true
				parrot = true
				creeper = true
				lightning_bolt = true
				enderman = true
				chicken = true
				trader_llama = true
				donkey = true
				chest_minecart = true
				fox = true
				tropical_fish = true
				slime = true
				pillager = true
				iron_golem = true
				area_effect_cloud = true
				zombified_piglin = true
				piglin = true
				cat = true
				zombie = true
				ender_pearl = true
				guardian = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				illusioner = true
				potion = true
				trident = true
				wolf = true
				villager = true
				skeleton_horse = true
				fishing_bobber = true
				zombie_villager = true
				elder_guardian = true
				boat = true
				polar_bear = true
				strider = true
				painting = true
				cave_spider = true
				cod = true
				witch = true
				spider = true

			[light_sources.settings.entities.vanilla_degus]
				degu = true

			[light_sources.settings.entities.endgoblintraders]
				end_goblin_trader = true

			[light_sources.settings.entities.unvotedandshelved]
				glare = true

			[light_sources.settings.entities.betteranimalsplus]
				deer = true
				feralwolf = true
				reindeer = true
				jellyfish = true
				octopus = true
				goose = true
				songbird = true
				badgerdirt = true
				eel_freshwater = true
				turkey_egg = true
				boar = true
				dragonfly = true
				whale = true
				lamprey = true
				butterfly = true
				pheasant = true
				blackbear = true
				pheasant_egg = true
				shark = true
				flying_fish = true
				piranha = true
				bobbit_worm = true
				goose_egg = true
				barracuda = true
				nautilus = true
				moose = true
				tarantula = true
				eel_saltwater = true
				badger = true
				squirrel = true
				brownbear = true
				walrus = true
				horseshoecrab = true
				turkey = true
				coyote = true
				squid_colossal = true
				lammergeier = true
				crab = true

			[light_sources.settings.entities.lovely_snails]
				snail = true

			[light_sources.settings.entities.adorn]
				seat = true

			[light_sources.settings.entities.ae2]
				charged_quartz = true
				growing_crystal = true

			[light_sources.settings.entities.bosses_of_mass_destruction]
				soul_star = true

			[light_sources.settings.entities.terrarianslimes]
				black_slime = true
				jungle_slime = true
				yellow_slime = true
				ice_slime = true
				baby_slime = true
				bomb = true
				mother_slime = true
				sand_slime = true
				green_slime = true
				red_slime = true
				umbrella_slime = true
				blue_slime = true
				purple_slime = true

			[light_sources.settings.entities.mythicmounts]
				netherbat = true
				ridinglizard = true
				courierbird = true
				moth = true
				nudibranch = true
				direwolf = true
				dragon = true
				griffon = true
				nightmare = true
				archelon = true
				geckotoalizard = true
				acencia = true

			[light_sources.settings.entities.capybara]
				capybara = true

			[light_sources.settings.entities.goblintraders]
				goblin_trader = true

			[light_sources.settings.entities.aqupd]
				caracal = true
				grizzly_bear = true

			[light_sources.settings.entities.betternether]
				naga_projectile = true
				firefly = true
				flying_pig = true
				chair = true
				hydrogen_jellyfish = true
				skull = true
				naga = true

			[light_sources.settings.entities.cspirit]
				reindeer = true
				christmas_tree = true

			[light_sources.settings.entities.adventurez]
				deer = true
				orc = true
				iguana = true
				amethyst_golem = true
				amethyst_shard = true
				summoner = true
				dragon = true
				blaze_guardian_shield = true

			[light_sources.settings.entities.earthtojavamobs]
				piebald_pig = true
				dairy_cow = true
				pink_footed_pig = true
				cream_cow = true
				flecked_sheep = true
				spotted_pig = true
				midnight_chicken = true
				umbra_cow = true
				skeleton_wolf = true
				rainbow_sheep = true
				mottled_pig = true
				gold_crested_chicken = true
				bold_striped_rabbit = true
				long_nosed_sheep = true
				muddy_pig = true
				freckled_rabbit = true
				amber_chicken = true
				wooly_cow = true
				sooty_pig = true
				vested_rabbit = true
				rotten_flesh_projectile = true
				patched_sheep = true
				bronzed_chicken = true
				jumbo_rabbit = true
				stormy_chicken = true
				horned_sheep = true
				harelequin_rabbit = true
				cookie_cow = true
				rocky_sheep = true
				pinto_cow = true
				fuzzy_sheep = true
				bone_spider = true
				albino_cow = true
				fancy_chicken = true
				jolly_llama = true
				tropical_slime = true
				inky_sheep = true
				sunset_cow = true
				skewbald_chicken = true
				pale_pig = true
				lobber_zombie = true

			[light_sources.settings.entities.exlinefurniture]
				entity_sit = true

			[light_sources.settings.entities.friendsandfoes]
				moobloom = true

			[light_sources.settings.entities.tinyskeletons]
				baby_skeleton = true

